package org.wildfly.camel.examples.jaxws.contractfirst;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630310
 * 2018-02-15T14:16:00.048-06:00
 * Generated source version: 3.1.5.redhat-630310
 * 
 */
@WebService(targetNamespace = "http://contractfirst.jaxws.examples.camel.wildfly.org/", name = "greeting")
@XmlSeeAlso({ObjectFactory.class})
public interface Greeting {

    @WebMethod(action = "urn:greetWithMessage")
    @RequestWrapper(localName = "greetWithMessage", targetNamespace = "http://contractfirst.jaxws.examples.camel.wildfly.org/", className = "org.wildfly.camel.examples.jaxws.contractfirst.GreetWithMessage")
    @ResponseWrapper(localName = "greetWithMessageResponse", targetNamespace = "http://contractfirst.jaxws.examples.camel.wildfly.org/", className = "org.wildfly.camel.examples.jaxws.contractfirst.GreetWithMessageResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String greetWithMessage(
        @WebParam(name = "message", targetNamespace = "")
        java.lang.String message,
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );
}
